/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedEmploiDuTempsRouteImport } from './routes/_authenticated/emploi-du-temps'
import { Route as AuthenticatedDisciplineRouteImport } from './routes/_authenticated/discipline'
import { Route as AuthenticatedDevoirsRouteImport } from './routes/_authenticated/devoirs'
import { Route as AuthenticatedClassesRouteImport } from './routes/_authenticated/classes'
import { Route as AuthenticatedCahierDeTextesRouteImport } from './routes/_authenticated/cahier-de-textes'
import { Route as AuthenticatedBulletinsRouteImport } from './routes/_authenticated/bulletins'
import { Route as AuthenticatedAppelRouteImport } from './routes/_authenticated/appel'
import { Route as AuthenticatedAnnuaireRouteImport } from './routes/_authenticated/annuaire'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedUUserIdRouteImport } from './routes/_authenticated/u.$userId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmploiDuTempsRoute =
  AuthenticatedEmploiDuTempsRouteImport.update({
    id: '/emploi-du-temps',
    path: '/emploi-du-temps',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDisciplineRoute = AuthenticatedDisciplineRouteImport.update({
  id: '/discipline',
  path: '/discipline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevoirsRoute = AuthenticatedDevoirsRouteImport.update({
  id: '/devoirs',
  path: '/devoirs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClassesRoute = AuthenticatedClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCahierDeTextesRoute =
  AuthenticatedCahierDeTextesRouteImport.update({
    id: '/cahier-de-textes',
    path: '/cahier-de-textes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBulletinsRoute = AuthenticatedBulletinsRouteImport.update({
  id: '/bulletins',
  path: '/bulletins',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppelRoute = AuthenticatedAppelRouteImport.update({
  id: '/appel',
  path: '/appel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnnuaireRoute = AuthenticatedAnnuaireRouteImport.update({
  id: '/annuaire',
  path: '/annuaire',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUUserIdRoute = AuthenticatedUUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/annuaire': typeof AuthenticatedAnnuaireRoute
  '/appel': typeof AuthenticatedAppelRoute
  '/bulletins': typeof AuthenticatedBulletinsRoute
  '/cahier-de-textes': typeof AuthenticatedCahierDeTextesRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/devoirs': typeof AuthenticatedDevoirsRoute
  '/discipline': typeof AuthenticatedDisciplineRoute
  '/emploi-du-temps': typeof AuthenticatedEmploiDuTempsRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/u/$userId': typeof AuthenticatedUUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/annuaire': typeof AuthenticatedAnnuaireRoute
  '/appel': typeof AuthenticatedAppelRoute
  '/bulletins': typeof AuthenticatedBulletinsRoute
  '/cahier-de-textes': typeof AuthenticatedCahierDeTextesRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/devoirs': typeof AuthenticatedDevoirsRoute
  '/discipline': typeof AuthenticatedDisciplineRoute
  '/emploi-du-temps': typeof AuthenticatedEmploiDuTempsRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/u/$userId': typeof AuthenticatedUUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/annuaire': typeof AuthenticatedAnnuaireRoute
  '/_authenticated/appel': typeof AuthenticatedAppelRoute
  '/_authenticated/bulletins': typeof AuthenticatedBulletinsRoute
  '/_authenticated/cahier-de-textes': typeof AuthenticatedCahierDeTextesRoute
  '/_authenticated/classes': typeof AuthenticatedClassesRoute
  '/_authenticated/devoirs': typeof AuthenticatedDevoirsRoute
  '/_authenticated/discipline': typeof AuthenticatedDisciplineRoute
  '/_authenticated/emploi-du-temps': typeof AuthenticatedEmploiDuTempsRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/u/$userId': typeof AuthenticatedUUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/annuaire'
    | '/appel'
    | '/bulletins'
    | '/cahier-de-textes'
    | '/classes'
    | '/devoirs'
    | '/discipline'
    | '/emploi-du-temps'
    | '/feed'
    | '/messages'
    | '/notes'
    | '/profil'
    | '/u/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/annuaire'
    | '/appel'
    | '/bulletins'
    | '/cahier-de-textes'
    | '/classes'
    | '/devoirs'
    | '/discipline'
    | '/emploi-du-temps'
    | '/feed'
    | '/messages'
    | '/notes'
    | '/profil'
    | '/u/$userId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/annuaire'
    | '/_authenticated/appel'
    | '/_authenticated/bulletins'
    | '/_authenticated/cahier-de-textes'
    | '/_authenticated/classes'
    | '/_authenticated/devoirs'
    | '/_authenticated/discipline'
    | '/_authenticated/emploi-du-temps'
    | '/_authenticated/feed'
    | '/_authenticated/messages'
    | '/_authenticated/notes'
    | '/_authenticated/profil'
    | '/_authenticated/u/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/emploi-du-temps': {
      id: '/_authenticated/emploi-du-temps'
      path: '/emploi-du-temps'
      fullPath: '/emploi-du-temps'
      preLoaderRoute: typeof AuthenticatedEmploiDuTempsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discipline': {
      id: '/_authenticated/discipline'
      path: '/discipline'
      fullPath: '/discipline'
      preLoaderRoute: typeof AuthenticatedDisciplineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devoirs': {
      id: '/_authenticated/devoirs'
      path: '/devoirs'
      fullPath: '/devoirs'
      preLoaderRoute: typeof AuthenticatedDevoirsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes': {
      id: '/_authenticated/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthenticatedClassesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cahier-de-textes': {
      id: '/_authenticated/cahier-de-textes'
      path: '/cahier-de-textes'
      fullPath: '/cahier-de-textes'
      preLoaderRoute: typeof AuthenticatedCahierDeTextesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bulletins': {
      id: '/_authenticated/bulletins'
      path: '/bulletins'
      fullPath: '/bulletins'
      preLoaderRoute: typeof AuthenticatedBulletinsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appel': {
      id: '/_authenticated/appel'
      path: '/appel'
      fullPath: '/appel'
      preLoaderRoute: typeof AuthenticatedAppelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/annuaire': {
      id: '/_authenticated/annuaire'
      path: '/annuaire'
      fullPath: '/annuaire'
      preLoaderRoute: typeof AuthenticatedAnnuaireRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/u/$userId': {
      id: '/_authenticated/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof AuthenticatedUUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAnnuaireRoute: typeof AuthenticatedAnnuaireRoute
  AuthenticatedAppelRoute: typeof AuthenticatedAppelRoute
  AuthenticatedBulletinsRoute: typeof AuthenticatedBulletinsRoute
  AuthenticatedCahierDeTextesRoute: typeof AuthenticatedCahierDeTextesRoute
  AuthenticatedClassesRoute: typeof AuthenticatedClassesRoute
  AuthenticatedDevoirsRoute: typeof AuthenticatedDevoirsRoute
  AuthenticatedDisciplineRoute: typeof AuthenticatedDisciplineRoute
  AuthenticatedEmploiDuTempsRoute: typeof AuthenticatedEmploiDuTempsRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedUUserIdRoute: typeof AuthenticatedUUserIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAnnuaireRoute: AuthenticatedAnnuaireRoute,
  AuthenticatedAppelRoute: AuthenticatedAppelRoute,
  AuthenticatedBulletinsRoute: AuthenticatedBulletinsRoute,
  AuthenticatedCahierDeTextesRoute: AuthenticatedCahierDeTextesRoute,
  AuthenticatedClassesRoute: AuthenticatedClassesRoute,
  AuthenticatedDevoirsRoute: AuthenticatedDevoirsRoute,
  AuthenticatedDisciplineRoute: AuthenticatedDisciplineRoute,
  AuthenticatedEmploiDuTempsRoute: AuthenticatedEmploiDuTempsRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedUUserIdRoute: AuthenticatedUUserIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
